"""add ai_engines

Revision ID: b993b96a3450
Revises: 80ca6447f581
Create Date: 2025-12-06 09:40:20.468542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b993b96a3450'
down_revision = '80ca6447f581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('api_url', sa.String(length=256), nullable=False),
    sa.Column('api_key', sa.String(length=256), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('source_domain', sa.String(length=100), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['crawl_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'source_domain', 'rule_id', name='unique_source_domain_rule')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_bindings')
    op.drop_table('ai_engines')
    # ### end Alembic commands ###
